myshop/mysite-20210810T003535Z-001/mysite/myshop/urls.py
from django.urls import path
from . import views

app_name = 'myshop'

urlpatterns = [
        path('',views.index,name='index'),
        path('',views.index,name='base'),
        path('detail/', views.IndexView.as_view(), name='index'),
        path('detail/<str:itemCode>', views.DetailView.as_view(), name='detail'),
        path('create/', views.create, name='create'),
        path('edit/<int:id>', views.edit, name='edit'),
        path('delete/<int:id>', views.delete, name='delete'),
        path('accounts/signup/', views.SignUp.as_view(), name='signup'),
]

myshop/mysite-20210810T003535Z-001/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('myshop/',include('myshop.urls')),
    path('admin/', admin.site.urls),
    path('',RedirectView.as_view(url='/myshop/')),
]

myshop/urls.py
from django.urls import path
from . import views

app_name = 'myshop'

urlpatterns = [
        path('',views.index,name='index'),
        path('',views.index,name='base'),
        path('detail/', views.IndexView.as_view(), name='index'),
        path('detail/<str:itemCode>', views.DetailView.as_view(), name='detail'),
        path('create/', views.create, name='create'),
        path('edit/<int:id>', views.edit, name='edit'),
        path('delete/<int:id>', views.delete, name='delete'),
        path('accounts/signup/', views.SignUp.as_view(), name='signup'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('myshop/',include('myshop.urls')),
    path('admin/', admin.site.urls),
    path('',RedirectView.as_view(url='/myshop/')),
]

myshop/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Memo(models.Model):
    name = models.CharField(max_length=200,verbose_name='名前:')
    dsc  = models.CharField(max_length=1000,verbose_name='説明:')
    date = models.DateField(blank=True, null=True)
    pic  = models.CharField(max_length=200,verbose_name='IMG:')
       
    def __str__(self):
        return self.name

myshop/mysite-20210810T003535Z-001/mysite/myshop/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Memo(models.Model):
    name = models.CharField(max_length=200,verbose_name='名前:')
    dsc  = models.CharField(max_length=1000,verbose_name='説明:')
    date = models.DateField(blank=True, null=True)
    pic  = models.CharField(max_length=200,verbose_name='IMG:')
       
    def __str__(self):
        return self.name

myshop/forms.py
from django import forms
from .models import Memo

class SearchForm(forms.Form):
    itemName = forms.CharField(label='商品名', max_length=200, required=True)
    
class AddForm(forms.ModelForm):  
    class Meta:
        model = Memo
        fields ="__all__"
        labels={
            'name':'商品名',
            'dsc':'説明',
            'date':'日付',
            'pic':'IMG'
        }
        widgets = {
            'date': forms.SelectDateWidget
        }
        
class SearchAForm(forms.Form):
    name = forms.CharField(label='商品名', max_length=200)
    
class SearchBForm(forms.Form):    
    date = forms.DateField(label='日付')
    

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

myshop/mysite-20210810T003535Z-001/mysite/myshop/forms.py
from django import forms
from .models import Memo

class SearchForm(forms.Form):
    itemName = forms.CharField(label='商品名', max_length=200, required=True)
    
class AddForm(forms.ModelForm):  
    class Meta:
        model = Memo
        fields ="__all__"
        labels={
            'name':'商品名',
            'dsc':'説明',
            'date':'日付',
            'pic':'IMG'
        }
        widgets = {
            'date': forms.SelectDateWidget
        }
        
class SearchAForm(forms.Form):
    name = forms.CharField(label='商品名', max_length=200)
    
class SearchBForm(forms.Form):    
    date = forms.DateField(label='日付')
    

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

myshop/mysite-20210810T003535Z-001/mysite/myshop/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.shortcuts import render
from django.views.generic import View
from .forms import SearchForm, SearchAForm
from .forms import AddForm
import json
import requests
from django.http import HttpResponse
from .models import Memo 
from . import forms
from django.views.generic import TemplateView
from django.core.paginator import Paginator
#from datetime import datetime



SEARCH_URL = 'https://app.rakuten.co.jp/services/api/IchibaItem/Search/20170706?format=json&applicationId=1095746777661250287'

def index(request):
    products = Memo.objects.all().order_by('date')
    searchForm = SearchAForm(request.GET)
    if searchForm.is_valid():
        search = searchForm.cleaned_data['name']
        product = Memo.objects.filter(name__icontains=search)
    else:
        searchForm = SearchAForm()
        product = Memo.objects.all().order_by('date')
    contents = {
        "title":'買い物一覧',
        'products':products,
        '編集':'編集',
        '商品名':'商品名',
        '説明':'説明',
        '日付':'日付',
        'IMG':'IMG',
        'searchForm':searchForm,
        'product':product
        }
    return render(request,'myshop/base.html',contents)

def edit(request, id):
    if request.method == 'POST':
        memo = get_object_or_404(Memo, pk=id)
        memoForm = AddForm(request.POST, instance=memo)
        if memoForm.is_valid():
            memoForm.save()
            return redirect(to='/myshop')
    else:
        memo = get_object_or_404(Memo, pk=id)  
        memoForm = AddForm(instance=memo)
        contents = {
            'Form': memoForm,
            'info': memo,
        }
        return render(request, 'myshop/edit.html', contents)

def delete(request, id):
    memo = get_object_or_404(Memo, pk=id)
    memo.delete()
    return redirect(to='/myshop')

def create(request):
    if request.method == "POST":
        obj = Memo()
        memo = AddForm(request.POST, instance=obj)
        memo.save()
        return redirect(to='/myshop')
    iName = request.GET.get('iName')
    iDsc = request.GET.get('iDsc')
    #idate= datetime.datetime.now()
    iC = request.GET.get('iC')
    
    initial_dict = dict(name=iName,dsc=iDsc[:50],pic=iC,)
    form = AddForm(initial=initial_dict)
    context = {
        'form':form,
        'back':request.META.get('HTTP_REFERER'),
    }
    return render(request, 'myshop/create.html', context)

def get_api_data(params):
    api = requests.get(SEARCH_URL, params=params).text
    result = json.loads(api)
    items = result['Items']
    return items

class IndexView(View):

    def get(self, request, *args, **kwargs):
        form = SearchForm(request.POST or None)

        return render(request, 'myshop/index.html', {
            'form': form,
            })

    def post(self, request, *args, **kwargs):
        form = SearchForm(request.POST or None)

        if form.is_valid():
            keyword = form.cleaned_data['itemName']
            params = {
                'keyword': keyword,
                'hits': 28,
            }
            items = get_api_data(params)
            item_data = []
            for i in items:
                item = i['Item']
                itemName = item['itemName']
                image = item['mediumImageUrls'][0]['imageUrl']
                itemCode = item['itemCode']
                itemPrice = item['itemPrice']
                query = {
                        'itemName': itemName,
                        'image': image,
                        'itemCode': itemCode,
                        'itemPrice': itemPrice,
                }
                item_data.append(query)

            return render(request, 'myshop/item.html', {
                'item_data': item_data,
                'keyword': keyword
            })

        return render(request, 'myshop/index.html', {
            'form': form
        })

class DetailView(View):
    	
    def get(self, request, *args, **kwargs):
        itemCode = self.kwargs['itemCode']
        params = {
            'itemCode': itemCode
        }

        items = get_api_data(params)
        items = items[0]
        item = items['Item']
        itemName = item['itemName']
        image = item['mediumImageUrls'][0]['imageUrl']
        itemPrice = item['itemPrice']
        shopName = item['shopName']
        itemCode = item['itemCode']
        itemCaption = item['itemCaption']
        itemUrl = item['itemUrl']
        reviewAverage = item['reviewAverage']
        reviewCount = item['reviewCount']

        item_data = {
            'itemName': itemName,
            'image': image,
            'itemPrice': itemPrice,
            'shopName': shopName,
            'itemCode': itemCode,
            'itemCaption': itemCaption,
            'itemUrl': itemUrl,
            'reviewAverage': reviewAverage,
            'reviewCount': reviewCount,
            'average': float(reviewAverage) * 20
        }
       
        return render(request, 'myshop/detail.html', {
             'item_data': item_data      
        })
 
"""----------------------------------------------------------"""
from django.contrib.auth import login
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from .forms import SignUpForm

class SignUp(CreateView):
    form_class = SignUpForm
    template_name = "myshop/signup.html" 
    success_url = reverse_lazy('top')

    def form_valid(self, form):
        user = form.save() # formの情報を保存
        login(self.request, user) # 認証
        self.object = user 
        return HttpResponseRedirect(self.get_success_url())
   
        
        

myshop/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.shortcuts import render
from django.views.generic import View
from .forms import SearchForm, SearchAForm
from .forms import AddForm
import json
import requests
from django.http import HttpResponse
from .models import Memo 
from . import forms
from django.views.generic import TemplateView
from django.core.paginator import Paginator
#from datetime import datetime



SEARCH_URL = 'https://app.rakuten.co.jp/services/api/IchibaItem/Search/20170706?format=json&applicationId=1095746777661250287'

def index(request):
    products = Memo.objects.all().order_by('date')
    searchForm = SearchAForm(request.GET)
    if searchForm.is_valid():
        search = searchForm.cleaned_data['name']
        product = Memo.objects.filter(name__icontains=search)
    else:
        searchForm = SearchAForm()
        product = Memo.objects.all().order_by('date')
    contents = {
        "title":'買い物一覧',
        'products':products,
        '編集':'編集',
        '商品名':'商品名',
        '説明':'説明',
        '日付':'日付',
        'IMG':'IMG',
        'searchForm':searchForm,
        'product':product
        }
    return render(request,'myshop/base.html',contents)

def edit(request, id):
    if request.method == 'POST':
        memo = get_object_or_404(Memo, pk=id)
        memoForm = AddForm(request.POST, instance=memo)
        if memoForm.is_valid():
            memoForm.save()
            return redirect(to='/myshop')
    else:
        memo = get_object_or_404(Memo, pk=id)  
        memoForm = AddForm(instance=memo)
        contents = {
            'Form': memoForm,
            'info': memo,
        }
        return render(request, 'myshop/edit.html', contents)

def delete(request, id):
    memo = get_object_or_404(Memo, pk=id)
    memo.delete()
    return redirect(to='/myshop')

def create(request):
    if request.method == "POST":
        obj = Memo()
        memo = AddForm(request.POST, instance=obj)
        memo.save()
        return redirect(to='/myshop')
    iName = request.GET.get('iName')
    iDsc = request.GET.get('iDsc')
    #idate= datetime.datetime.now()
    iC = request.GET.get('iC')
    
    initial_dict = dict(name=iName,dsc=iDsc[:50],pic=iC,)
    form = AddForm(initial=initial_dict)
    context = {
        'form':form,
        'back':request.META.get('HTTP_REFERER'),
    }
    return render(request, 'myshop/create.html', context)

def get_api_data(params):
    api = requests.get(SEARCH_URL, params=params).text
    result = json.loads(api)
    items = result['Items']
    return items

class IndexView(View):

    def get(self, request, *args, **kwargs):
        form = SearchForm(request.POST or None)

        return render(request, 'myshop/index.html', {
            'form': form,
            })

    def post(self, request, *args, **kwargs):
        form = SearchForm(request.POST or None)

        if form.is_valid():
            keyword = form.cleaned_data['itemName']
            params = {
                'keyword': keyword,
                'hits': 28,
            }
            items = get_api_data(params)
            item_data = []
            for i in items:
                item = i['Item']
                itemName = item['itemName']
                image = item['mediumImageUrls'][0]['imageUrl']
                itemCode = item['itemCode']
                itemPrice = item['itemPrice']
                query = {
                        'itemName': itemName,
                        'image': image,
                        'itemCode': itemCode,
                        'itemPrice': itemPrice,
                }
                item_data.append(query)

            return render(request, 'myshop/item.html', {
                'item_data': item_data,
                'keyword': keyword
            })

        return render(request, 'myshop/index.html', {
            'form': form
        })

class DetailView(View):
    	
    def get(self, request, *args, **kwargs):
        itemCode = self.kwargs['itemCode']
        params = {
            'itemCode': itemCode
        }

        items = get_api_data(params)
        items = items[0]
        item = items['Item']
        itemName = item['itemName']
        image = item['mediumImageUrls'][0]['imageUrl']
        itemPrice = item['itemPrice']
        shopName = item['shopName']
        itemCode = item['itemCode']
        itemCaption = item['itemCaption']
        itemUrl = item['itemUrl']
        reviewAverage = item['reviewAverage']
        reviewCount = item['reviewCount']

        item_data = {
            'itemName': itemName,
            'image': image,
            'itemPrice': itemPrice,
            'shopName': shopName,
            'itemCode': itemCode,
            'itemCaption': itemCaption,
            'itemUrl': itemUrl,
            'reviewAverage': reviewAverage,
            'reviewCount': reviewCount,
            'average': float(reviewAverage) * 20
        }
       
        return render(request, 'myshop/detail.html', {
             'item_data': item_data      
        })
 
"""----------------------------------------------------------"""
from django.contrib.auth import login
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from .forms import SignUpForm

class SignUp(CreateView):
    form_class = SignUpForm
    template_name = "myshop/signup.html" 
    success_url = reverse_lazy('top')

    def form_valid(self, form):
        user = form.save() # formの情報を保存
        login(self.request, user) # 認証
        self.object = user 
        return HttpResponseRedirect(self.get_success_url())
   
        
        

myshop/mysite-20210810T003535Z-001/mysite/myshop/templates/myshop/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
         <link rel="stylesheet" href="{% static 'css/style.css' %}">
	<title>ホーム</title>
</head>
<body>
{% block cont %}{% endblock %}
</body>
<body>	
	</nav>
	<main>
		<center>
			<a class="title" href="/myshop">お買い物ダイアリー</a>
	<img src="/media/img/a.png">					
		</div>
		</center>
		<div class="container">
			{% block content %}
			{% endblock %}
		</div>
		{% if searchForm %}
		<center>
		<button type=“button” class="kensakubtn" onclick="location.href='http://127.0.0.1:8000/myshop/detail'">追加</button>
		</center>
		<center>
	  	<form action='{% url "myshop:base" %}' method='get'>
	    		{{ searchForm }}
	    		<input type="submit" value="検索" />	 	 
	 	</form>
	 	</center>

   		{% endif %}
		
		<center>
		<h2>{{ title }}</h2>
		  <table class="flexbox" border='2'>
			{% for p in product %}
			  <tr>
			   <th>{{IMG}}</th>
			   <td><a href="{% url 'myshop:edit' p.id %}"><img src="{{ p.pic }}"></a></td>
			  </tr>
		          <tr>
			   <th>{{商品名}}</th>
			   <td>{{ p.name }}</td>
			  </tr>
		          <tr>
		           <th>{{ 説明 }}</th>
			   <td>{{ p.dsc }}</td>
			  </tr>
		          <tr>
			   <th>{{ 日付 }}</th>
			   <td>{{ p.date }}</td>
			  </tr>
			{% endfor %}
		  </table>
		</center>
		   
	</main>
	
	<footer>
	        <center>
		<a href="/myshop" class="navbar-brand">ホーム</a>
	        </center>	
	</footer>

	{% block extra_js %}
	{% endblock %}

</body>
</html>

myshop/mysite-20210810T003535Z-001/mysite/myshop/templates/myshop/create.html
{% extends 'myshop/base.html' %}

{% block content %}

{% load bootstrap4 %}
<html>
    <center>
    <h3>登録画面</h3>
    {{ item_data.itemName }}

    <form action='{% url "myshop:create" %}' method='post' class='form'>
        
        <!-- ??? -->
        {% csrf_token %}
        <img src="{{ iC }}">
        {% bootstrap_form form %}
        <button type='submit' class='btn btn-outline-primary' onClick="return confirm('追加してよろしいでしょうか??')">保存</button>
        <input type="button" value="戻る" onClick="javascript:history.back();">
    </form>
    <form method="post" enctype="multipart/form-data">
       <input type="file"  name="upfile" accept="image/*">
       <button type="submit">写真アップロード</button>
    </form>
    </center>

</html>

{% endblock %}

myshop/mysite-20210810T003535Z-001/mysite/myshop/templates/myshop/detail.html
{% extends 'myshop/base.html' %}

{% block content %}

<div class="my-5">
<h3>{{ item_data.itemName }}</h3>
		<p class="mb-3">{{ item_data.shopName }}</p>
	<div class="row">
	 
		
	<div class="col-6 left">
			<img src="{{ item_data.image }}" alt="" width="200px" height="200px" class="img-fluid">
		</div>

	<div class="col-6 right">
			<div class="card">
				<div class="card-body px-2 py-1">
                                     
				     <hr>
				     {% if not item_data.reviewCount == 0 %}
				         <div class="d-flex flex-row">
						 <div class="star-rating">
							 <div class="star-rating-front text-warning" style="width: {{ item_data.average }}%">★★★★★</div>
							 <div class="star-rating-back">★★★★★</div>
					         </div>
					         <div class="average ml-2 text-danger">
							 {{ item_data.reviewAverage|floatformat:2 }}
					         </div>
						 <div class="d-flex align-items-center ml-2">
							 {{ item_data.reviewCount }}件
						 </div>

			                 </div>
				     {% else %}
				         <p>Non Review</p>
				     {% endif %}
				     <a href="{{ item_data.itemUrl }}" class="btn-sm btn-primary">サイトへ</a>
				     <p class="mt-3">価格:<span class="text-danger font-weight-bold h3">{{ item_data.itemPrice }} 円
				     
				     <a href='{% url "myshop:create" %}?iName={{item_data.itemName}}&iDsc={{item_data.itemCaption}}&iC={{item_data.image}}' class="btn btn-primary">myListに追加</a>
                                </div>
			</div>
		</div>
	</div>

	{% if item_data.itemCaption %}
	    <div class="mb-5">
		    <h5>商品説明</h5>
		    <hr>
		    <p>{{ item_data.itemCaption }}</p>
	   </div>
	{% endif %}

	<div class="mb-5">
		<hr>
		<p>コード: {{ item_data.itemCode }}</p>
        </div>
</div>


{% endblock %}

myshop/mysite-20210810T003535Z-001/mysite/myshop/templates/myshop/edit.html
{% extends 'myshop/base.html' %}
{% block content %}
{% load bootstrap4 %}
<div class="text-center my-5">
<html>
    <h2>~編集~</h2>
 
    <form action="{% url 'myshop:edit' info.id %}" method='post' class='form'>
        <!-- ユーザー編集フォームを表示 -->
        {% csrf_token %}
        {% bootstrap_form Form %}
        <button type='submit' class='btn btn-outline-primary'>更新</button>
        <td><a href="{% url 'myshop:delete' info.id %}" class='btn btn-outline-primary'>削除</a></td>
    </form>
    </form>
</html>
</div>
{% endblock %}

myshop/mysite-20210810T003535Z-001/mysite/myshop/templates/myshop/index.html
{% extends "myshop/base.html" %} 
{% load widget_tweaks %} 
{% block content %}



<div class="text-center my-5">
  <form method="post">
    {% csrf_token %}
    <div class="align-items-center">
      {% render_field form.itemName class="form-control" placeholder="キーワードから探す" %}
      <button class="kensakubtn" type="submit">検索</button>
      {{ contents.products }}
    </div>
  </form>
</div>

{% endblock %}

myshop/mysite-20210810T003535Z-001/mysite/myshop/templates/myshop/item.html
{% extends 'myshop/base.html' %}

{% block content %}

<div class="text-center my-5">
	<div class="mb-5">
		<h3>「{{ keyword }}」の検索結果</h3>
	</div>
	<div class="row">
		{% for item in item_data %}
		    <div class="col-4 mb-4">
			    <div class="card img-thumbbail itemlist h-100">
				    <img src="{{ item.image }}" alt="" class="card-img-top card-thum">
				    <div class="card-body text-center px-2 py-3">
					    <h5 class="font-weigh-bold">{{ item.itemName }}</h5>
					    <p class="mt-3">価格:<span class="text-danger h5">{{ item.itemPrice }} 円
			            </div>
				    <a href="{% url 'myshop:detail' item.itemCode %}" class="stretched-link"></a>
	                    </div>
		    </div>
		{% empty %}
		    <p>Non data</p>
		{% endfor %}
        </div>
</div>

{% endblock %}

myshop/mysite-20210810T003535Z-001/mysite/myshop/templates/myshop/signup.html
{% extends 'myshop/base.html' %}

{% block cont %}
<main>
...
...
{# signup処理部分 #}
<form method="post" action="{% url 'signup' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.email.label_tag }}</td>
    <td>{{ form.email }}</td>
</tr>
<tr>
    <td>{{ form.password1.label_tag }}</td>
    <td>{{ form.password1 }}</td>
</tr>
<tr>
    <td>{{ form.password2.label_tag }}</td>
    <td>{{ form.password2 }}</td>
</tr>
</table>

<input type="submit" value="login" />

{# エラーメッセージを表示 #}
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <p>{{ error }}</p>
        {% endfor %}
     {% endfor %}
{% endif %} 
</form>
{% endblock %}